"""
examine_scan.py
===============

This script reads a surface scan data file generated by the Keyence confocal displacement sensor. The data file is a .csv file with the first 12 rows as header. The script reads the height data and plots it using matplotlib.

Syntax
------
```console
python examine_scan.py data_path
```

Edit
----
May 01, 2024: Initial commit.
Oct 09, 2024: Add docstring.
"""

import matplotlib.pyplot as plt
import pandas as pd
import sys

data_path = sys.argv[1]
surface = pd.read_csv(data_path, usecols=[1], skiprows=12, names=["height"])
plt.plot(surface)
plt.show()